#!/usr/bin/env bash
# generate-network-docs.sh - Auto-generates NETWORK_ARCHITECTURE.md from live system state
# Usage: ./generate-network-docs.sh [hostname]
# Default hostname: halvarm

set -euo pipefail

HOST="${1:-halvarm}"
OUTPUT_DIR="$(dirname "$0")"
OUTPUT_FILE="$OUTPUT_DIR/NETWORK_ARCHITECTURE.md"
TIMESTAMP=$(date -Iseconds)

echo "Querying $HOST for network state..."

# Collect data
PORTS=$(ssh "$HOST" 'ss -tlnp 2>/dev/null | grep LISTEN | awk "{print \$4, \$6}" | sort -t: -k2 -n' 2>/dev/null || echo "")
CONTAINERS=$(ssh "$HOST" 'docker ps --format "{{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null' || echo "")
RSRCH_CONTAINERS=$(echo "$CONTAINERS" | grep -E "rsrch" || echo "")
CDP_INFO=$(ssh "$HOST" 'curl -s http://localhost:9221/json/version 2>/dev/null' || echo '{"error":"not available"}')
RSRCH_HEALTH=$(ssh "$HOST" 'curl -s http://localhost:3030/health 2>/dev/null' || echo '{"error":"not available"}')
VNC_PROCESS=$(ssh "$HOST" 'ps aux | grep "x11vnc.*5900" | grep -v grep | head -1' 2>/dev/null || echo "")
CHROME_PROCESS=$(ssh "$HOST" 'ps aux | grep "remote-debugging-port" | grep -v grep | head -1' 2>/dev/null || echo "")

# Extract key ports
API_PORT=$(echo "$PORTS" | grep -E ":3030" | head -1 | awk '{print $1}' | sed 's/.*://' || echo "N/A")
CDP_PORT=$(echo "$CDP_INFO" | grep -q error && echo "N/A" || echo "9221")
VNC_PORT=$(echo "$VNC_PROCESS" | grep -oE "rfbport [0-9]+" | awk '{print $2}' || echo "N/A")
FALKOR_PORT=$(echo "$PORTS" | grep -E ":6379" | head -1 | awk '{print $1}' | sed 's/.*://' || echo "N/A")

# Generate markdown
cat > "$OUTPUT_FILE" << EOF
# Rsrch Network Architecture on $HOST

> **Auto-generated**: $TIMESTAMP
> **Generated by**: \`generate-network-docs.sh\`

## Quick Reference

| Service | Port | Status |
|---------|------|--------|
| **rsrch API** | \`${API_PORT:-N/A}\` | $(echo "$RSRCH_HEALTH" | grep -q '"status":"ok"' && echo "✅ OK" || echo "⚠️ Check") |
| **Chrome CDP** | \`${CDP_PORT:-N/A}\` | $(echo "$CDP_INFO" | grep -q Browser && echo "✅ Connected" || echo "❌ Not available") |
| **VNC** | \`${VNC_PORT:-N/A}\` | $([ -n "$VNC_PROCESS" ] && echo "✅ Running" || echo "❌ Not running") |
| **FalkorDB** | \`${FALKOR_PORT:-N/A}\` | $(echo "$RSRCH_HEALTH" | grep -q '"falkordb":"ok"' && echo "✅ OK" || echo "⚠️ Check") |

## Architecture Diagram

\`\`\`
┌─────────────────────────────────────────────────────────────────────────┐
│                           $HOST SERVER                                   │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   ┌──────────────────────┐         ┌──────────────────────────────────┐ │
│   │  rsrch-prod          │         │  Authenticated Chrome            │ │
│   │  (--network host)    │   CDP   │  (Long-running, VNC visible)     │ │
│   │                      │◄───────►│                                  │ │
│   │  Port ${API_PORT:-????} (API)     │ :${CDP_PORT:-????}  │  - Google authenticated         │ │
│   │                      │         │  - Gemini PRO access             │ │
│   └──────────────────────┘         └──────────────────────────────────┘ │
│            ▲                                      ▲                      │
│            │                                      │ x11vnc               │
│   ┌────────┴────────┐              ┌──────────────┴───────────────────┐ │
│   │  FalkorDB       │              │  VNC Server                      │ │
│   │  Port ${FALKOR_PORT:-????}      │              │  Port ${VNC_PORT:-????}                        │ │
│   └─────────────────┘              └──────────────────────────────────┘ │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘
\`\`\`

## Live Container Status

\`\`\`
$(echo "$RSRCH_CONTAINERS" | column -t -s $'\t' || echo "No rsrch containers found")
\`\`\`

## Chrome CDP Details

\`\`\`json
$CDP_INFO
\`\`\`

## rsrch API Health

\`\`\`json
$RSRCH_HEALTH
\`\`\`

## Starting rsrch-prod (Reference)

\`\`\`bash
# CORRECT: Connect to existing authenticated browser
docker run -d --name rsrch-prod --network host \\
  -e PORT=3030 \\
  -e BROWSER_CDP_ENDPOINT=http://localhost:9221 \\
  -v /home/sim/.rsrch/profiles:/opt/rsrch/profiles \\
  ghcr.io/simik394/osobni_wf/rsrch:vnc node dist/cli.js serve
\`\`\`

## All Listening Ports

\`\`\`
$(echo "$PORTS" | head -20 || echo "No ports data")
\`\`\`

## Troubleshooting

| Symptom | Cause | Fix |
|---------|-------|-----|
| "Browser not initialized" | rsrch not connected to CDP | Restart with \`BROWSER_CDP_ENDPOINT\` |
| "Gemini requires authentication" | New browser launched | Use existing Chrome on 9221 |
| VNC shows nothing | Xvfb not running | Check display processes |
| Port 3030 in use | Old container running | \`docker stop rsrch-prod\` |

---
*Regenerate this file: \`./generate-network-docs.sh $HOST\`*
EOF

echo "Generated: $OUTPUT_FILE"
echo "Timestamp: $TIMESTAMP"
