classDiagram
    class ArtifactRegistry
    class PerplexityClient
    class GeminiClient
    class GraphStore
    class JobQueue
    class NotebookLMClient
    class StringWriter
    class StringReader
    class OneObjectCache
    class HebrewHelper
    class IslamicHelper
    class IslamicUmalquraHelper
    class IslamicTblaHelper
    class IslamicCivilHelper
    class IslamicRgsaHelper
    class IslamicCcHelper
    class PersianHelper
    class IndianHelper
    class EthioaaHelper
    class CopticHelper
    class EthiopicHelper
    class RocHelper
    class BuddhistHelper
    class GregoryHelper
    class JapaneseHelper
    class ChineseHelper
    class DangiHelper
    class NonIsoCalendar
    class Duration
    class Instant
    class DateTimeFormatImpl
    class LegacyDateImpl
    class PlainDate
    class PlainDateTime
    class PlainMonthDay
    class PlainTime
    class PlainYearMonth
    class TimeDuration
    class ZonedDateTime
    class CLI
    class InstalledBrowser
    class Cache
    class Process
    class TimeoutError
    class CLI
    class InstalledBrowser
    class Cache
    class Process
    class TimeoutError
    class CLI
    class InstalledBrowser
    class Cache
    class Process
    class TimeoutError
    class BufferComposer
    class StringComposer
    class RESP2Decoder
    class RedisCommandsQueue
    class RedisClient
    class RedisClientMultiCommand
    class PubSub
    class RedisSocket
    class RedisClusterSlots
    class RedisCluster
    class RedisClusterMultiCommand
    class AbortError
    class WatchError
    class ConnectionTimeoutError
    class ClientClosedError
    class ClientOfflineError
    class DisconnectsClientError
    class SocketClosedUnexpectedlyError
    class RootNodesUnavailableError
    class ReconnectStrategyError
    class ErrorReply
    class MultiErrorReply
    class RedisMultiCommand
    class Graph
    class Example
    class QuickJSAsyncContext
    class ContextMemory
    class QuickJSContext
    class QuickJSDeferredPromise
    class QuickJSUnwrapError
    class QuickJSWrongOwner
    class QuickJSUseAfterFree
    class QuickJSNotImplemented
    class QuickJSAsyncifyError
    class QuickJSAsyncifySuspended
    class QuickJSMemoryLeakDetected
    class QuickJSFFI
    class Lifetime
    class StaticLifetime
    class WeakLifetime
    class Scope
    class ModuleMemory
    class QuickJSAsyncWASMModule
    class TestQuickJSWASMModule
    class QuickJSEmscriptenModuleCallbacks
    class QuickJSModuleCallbacks
    class QuickJSWASMModule
    class QuickJSAsyncRuntime
    class QuickJSRuntime
    class Entry
    class ZipFile
    class Parser
    class TokenType
    class Token
    class Agent
    class EventListener
    class Event
    class CustomEvent
    class EventTarget
    class Event
    class EventListener
    class Client
    class FileInfo
    class FTPError
    class FTPContext
    class ProgressTracker
    class StringWriter
    class TransferResolver
    class Buffer
    class BidiNoOpParser
    class BidiServer
    class CommandProcessor
    class OutgoingMessage
    class BrowserProcessor
    class CdpProcessor
    class BrowsingContextImpl
    class BrowsingContextProcessor
    class BrowsingContextStorage
    class CdpTarget
    class ActionDispatcher
    class InputProcessor
    class NoneSource
    class KeySource
    class PointerSource
    class WheelSource
    class InputState
    class InputStateManager
    class LogManager
    class NetworkManager
    class NetworkProcessor
    class NetworkRequest
    class NetworkStorage
    class PermissionsProcessor
    class ChannelProxy
    class DedicatedWorkerRealm
    class PreloadScript
    class PreloadScriptStorage
    class Realm
    class RealmStorage
    class ScriptProcessor
    class WindowRealm
    class EventWrapper
    class EventManager
    class SessionProcessor
    class SubscriptionManager
    class StorageProcessor
    class BrowserInstance
    class MapperServerCdpConnection
    class SimpleTransport
    class WebSocketServer
    class BidiParser
    class WindowBidiTransport
    class WindowCdpTransport
    class CloseError
    class MapperCdpClient
    class MapperCdpConnection
    class Exception
    class InvalidArgumentException
    class InvalidSessionIdException
    class MoveTargetOutOfBoundsException
    class NoSuchAlertException
    class NoSuchElementException
    class NoSuchFrameException
    class NoSuchHandleException
    class NoSuchHistoryEntryException
    class NoSuchInterceptException
    class NoSuchNodeException
    class NoSuchRequestException
    class NoSuchScriptException
    class NoSuchUserContextException
    class SessionNotCreatedException
    class UnknownCommandException
    class UnknownErrorException
    class UnableToCaptureScreenException
    class UnableToCloseBrowserException
    class UnsupportedOperationException
    class NoSuchStoragePartitionException
    class UnableToSetCookieException
    class UnableToSetFileInputException
    class UnderspecifiedStoragePartitionException
    class Buffer
    class DefaultMap
    class Deferred
    class EventEmitter
    class IdWrapper
    class Mutex
    class ProcessingQueue
    class WebSocketTransport
    class UI
    class Extractor
    class Cluster
    class NullClient
    class Sentinel
    class Single
    class FalkorDB
    class Graph
    class Pool
    class DefaultEvictor
    class Deferred
    class Deque
    class DequeIterator
    class DoublyLinkedList
    class DoublyLinkedListIterator
    class Pool
    class PoolDefaults
    class PoolOptions
    class PooledResource
    class PriorityQueue
    class Queue
    class ResourceLoan
    class ResourceRequest
    class ExtendableError
    class TimeoutError
    class MaxBufferError
    class DataReadable
    class HTTPError
    class NotFoundError
    class NotModifiedError
    class HttpProxyAgent
    class HttpsProxyAgent
    class AddressError
    class Address4
    class Address6
    class AddressError
    class Address4
    class Address6
    class ZeroArray
    class Stack
    class LRUCache
    class Blob
    class Headers
    class Response
    class Request
    class Blob
    class Headers
    class Response
    class Request
    class PacProxyAgent
    class AgentParser
    class ClaudeGenerator
    class OpencodeGenerator
    class CopilotGenerator
    class VSCodeGenerator
    class FullConfigInternal
    class FullProjectInternal
    class FixturePool
    class PoolBuilder
    class ProcessRunner
    class Base
    class Suite
    class TestCase
    class TestTypeImpl
    class Watcher
    class SnapshotRecorder
    class ArtifactsRecorder
    class EventEmitter
    class StringInternPool
    class JsonStringInternalizer
    class TeleReporterReceiver
    class TeleSuite
    class TeleTestCase
    class TeleTestStep
    class TeleTestResult
    class TeleSuiteUpdater
    class TestServerConnectionClosedError
    class WebSocketTestServerTransport
    class TestServerConnection
    class TestTree
    class LoaderMain
    class ExpectMetaInfoProxyHandler
    class ExpectError
    class SnapshotHelper
    class BaseContextFactory
    class IsolatedContextFactory
    class CdpContextFactory
    class RemoteContextFactory
    class PersistentContextFactory
    class SharedContextFactory
    class BrowserServerBackend
    class Context
    class InputRecorder
    class Response
    class SessionLog
    class Tab
    class CDPRelayServer
    class ExtensionConnection
    class ExtensionContextFactory
    class SimpleBrowserContextFactory
    class InProcessTransport
    class InProcessServerTransport
    class ProxyBackend
    class StringWriteStream
    class TestServerBackend
    class GeneratorJournal
    class TestContext
    class WebServerPlugin
    class TerminalReporter
    class BlobReporter
    class DotReporter
    class EmptyReporter
    class GitHubLogger
    class GitHubReporter
    class HtmlReporter
    class HtmlBuilder
    class Base64Encoder
    class InternalReporter
    class JSONReporter
    class JUnitReporter
    class LineReporter
    class ListReporter
    class ListModeReporter
    class MarkdownReporter
    class UniqueFileNameGenerator
    class IdsPatcher
    class AttachmentPathPatcher
    class PathSeparatorPatcher
    class GlobalErrorPatcher
    class JsonEventPatchers
    class BlobModernizer
    class Multiplexer
    class ReporterV2Wrapper
    class TeleReporterEmitter
    class Dispatcher
    class JobDispatcher
    class FailureTracker
    class LastRunReporter
    class InProcessLoaderHost
    class OutOfProcessLoaderHost
    class ProcessHost
    class SigIntWatcher
    class FixedNodeSIGINTHandler
    class TaskRunner
    class TimeoutWatcher
    class TestRun
    class TestRunner
    class TestServer
    class TestServerDispatcher
    class UIModeReporter
    class InMemoryTransport
    class WorkerHost
    class PortTransport
    class Fixture
    class FixtureRunner
    class TestInfoImpl
    class TestStepInfoImpl
    class TestSkipError
    class StepSkipError
    class TestTracing
    class TimeoutManager
    class TimeoutManagerError
    class WorkerMain
    class AndroidServerLauncherImpl
    class BrowserServerLauncherImpl
    class Android
    class AndroidDevice
    class AndroidSocket
    class AndroidInput
    class AndroidWebView
    class Artifact
    class Browser
    class BrowserContext
    class BrowserType
    class CDPSession
    class ChannelOwner
    class Clock
    class Root
    class DummyChannelOwner
    class Connection
    class ConsoleMessage
    class Coverage
    class Dialog
    class Download
    class Electron
    class ElectronApplication
    class ElementHandle
    class TimeoutError
    class TargetClosedError
    class EventEmitter
    class OnceWrapper
    class APIRequest
    class APIRequestContext
    class APIResponse
    class FileChooser
    class Frame
    class HarRouter
    class Keyboard
    class Mouse
    class Touchscreen
    class JSHandle
    class JsonPipe
    class LocalUtils
    class Locator
    class FrameLocator
    class Request
    class Route
    class WebSocketRoute
    class WebSocketRouteHandler
    class Response
    class WebSocket
    class RouteHandler
    class RawHeaders
    class Page
    class BindingCall
    class Playwright
    class Selectors
    class Stream
    class TimeoutSettings
    class Tracing
    class Video
    class Waiter
    class WebError
    class JsonPipeTransport
    class WebSocketTransport
    class Worker
    class WritableStream
    class PlaywrightClient
    class ValidationError
    class PlaywrightConnection
    class PlaywrightServer
    class Android
    class AndroidDevice
    class AndroidBrowser
    class ClankBrowserProcess
    class AdbBackend
    class AdbDevice
    class BufferedSocketWrapper
    class Artifact
    class BidiBrowser
    class BidiBrowserContext
    class BidiChromium
    class BidiConnection
    class BidiSession
    class BidiExecutionContext
    class BidiFirefox
    class RawKeyboardImpl
    class RawMouseImpl
    class RawTouchscreenImpl
    class BidiNetworkManager
    class BidiRequest
    class BidiRouteImpl
    class BidiTransportImpl
    class BidiConnection
    class CdpTransportImpl
    class BidiPage
    class BidiPDF
    class BidiDeserializer
    class UnserializableError
    class BidiSerializer
    class Browser
    class BrowserContext
    class BrowserType
    class Chromium
    class CRBrowser
    class CRBrowserContext
    class CRConnection
    class CRSession
    class CDPSession
    class CRCoverage
    class JSCoverage
    class CSSCoverage
    class CRDevTools
    class DragManager
    class CRExecutionContext
    class RawKeyboardImpl
    class RawMouseImpl
    class RawTouchscreenImpl
    class CRNetworkManager
    class InterceptableRequest
    class RouteImpl
    class ResponseExtraInfoTracker
    class CRPage
    class FrameSession
    class CRPDF
    class CRServiceWorker
    class VideoRecorder
    class Clock
    class CSharpLanguageGenerator
    class CSharpFormatter
    class JavaLanguageGenerator
    class JavaScriptLanguageGenerator
    class JavaScriptFormatter
    class JsonlLanguageGenerator
    class PythonLanguageGenerator
    class PythonFormatter
    class ConsoleMessage
    class Cookie
    class CookieStore
    class DebugController
    class Debugger
    class Dialog
    class DialogManager
    class AndroidDispatcher
    class AndroidDeviceDispatcher
    class SocketSdkObject
    class AndroidSocketDispatcher
    class ArtifactDispatcher
    class BrowserContextDispatcher
    class BrowserDispatcher
    class BrowserTypeDispatcher
    class CDPSessionDispatcher
    class DebugControllerDispatcher
    class DialogDispatcher
    class Dispatcher
    class RootDispatcher
    class DispatcherConnection
    class ElectronDispatcher
    class ElectronApplicationDispatcher
    class ElementHandleDispatcher
    class FrameDispatcher
    class JSHandleDispatcher
    class JsonPipeDispatcher
    class LocalUtilsDispatcher
    class RequestDispatcher
    class ResponseDispatcher
    class RouteDispatcher
    class WebSocketDispatcher
    class APIRequestContextDispatcher
    class PageDispatcher
    class WorkerDispatcher
    class BindingCallDispatcher
    class PlaywrightDispatcher
    class SocksSupportDispatcher
    class StreamSdkObject
    class StreamDispatcher
    class TracingDispatcher
    class WebSocketRouteDispatcher
    class WritableStreamSdkObject
    class WritableStreamDispatcher
    class NonRecoverableDOMError
    class FrameExecutionContext
    class ElementHandle
    class Download
    class ElectronApplication
    class Electron
    class CustomError
    class TimeoutError
    class TargetClosedError
    class APIRequestContext
    class SafeEmptyStreamTransform
    class BrowserContextAPIRequestContext
    class GlobalAPIRequestContext
    class FileChooser
    class FFBrowser
    class FFBrowserContext
    class FFConnection
    class FFSession
    class FFExecutionContext
    class RawKeyboardImpl
    class RawMouseImpl
    class RawTouchscreenImpl
    class FFNetworkManager
    class InterceptableRequest
    class FFRouteImpl
    class FFPage
    class Firefox
    class MultipartFormData
    class FrameSelectors
    class NavigationAbortedError
    class FrameManager
    class Frame
    class SignalBarrier
    class HarRecorder
    class HarTracer
    class HarBackend
    class Helper
    class Keyboard
    class Mouse
    class Touchscreen
    class SdkObject
    class ExecutionContext
    class JSHandle
    class JavaScriptErrorInEvaluate
    class Request
    class Route
    class Response
    class WebSocket
    class Page
    class Worker
    class PageBinding
    class InitScript
    class FrameThrottler
    class PipeTransport
    class Playwright
    class ProgressController
    class ProtocolError
    class Chat
    class Connection
    class RecorderApp
    class ProgrammaticRecorderApp
    class RecorderSignalProcessor
    class ThrottledFile
    class Recorder
    class Registry
    class Screenshotter
    class TaskQueue
    class Selectors
    class SocksProxyConnection
    class ClientCertificatesProxy
    class SocksInterceptor
    class Snapshotter
    class Tracing
    class InMemorySnapshotter
    class StdinServer
    class WebSocketTransport
    class DER
    class DebugLogger
    class RecentLogsCollector
    class EventsHelper
    class SerializedFS
    class HttpHappyEyeballsAgent
    class HttpsHappyEyeballsAgent
    class HttpServer
    class ImageChannel
    class FastStats
    class NodeZone
    class ReadableStreamImpl
    class WritableStreamImpl
    class PipeTransport
    class SocksConnection
    class SocksProxy
    class SocksProxyHandler
    class WSServer
    class ZipFile
    class Zone
    class WebKit
    class WKBrowser
    class WKBrowserContext
    class WKConnection
    class WKSession
    class WKExecutionContext
    class RawKeyboardImpl
    class RawMouseImpl
    class RawTouchscreenImpl
    class WKInterceptableRequest
    class WKRouteImpl
    class WKPage
    class WKProvisionalPage
    class WKWorkers
    class KeyParser
    class ParserError
    class InvalidSelectorError
    class InvalidCharacterError
    class CSSParserToken
    class BadStringToken
    class BadURLToken
    class WhitespaceToken
    class CDOToken
    class CDCToken
    class ColonToken
    class SemicolonToken
    class CommaToken
    class GroupingToken
    class OpenCurlyToken
    class CloseCurlyToken
    class OpenSquareToken
    class CloseSquareToken
    class OpenParenToken
    class CloseParenToken
    class IncludeMatchToken
    class DashMatchToken
    class PrefixMatchToken
    class SuffixMatchToken
    class SubstringMatchToken
    class ColumnToken
    class EOFToken
    class DelimToken
    class StringValuedToken
    class IdentToken
    class FunctionToken
    class AtKeywordToken
    class HashToken
    class StringToken
    class URLToken
    class NumberToken
    class PercentageToken
    class DimensionToken
    class JavaScriptLocatorFactory
    class PythonLocatorFactory
    class JavaLocatorFactory
    class CSharpLocatorFactory
    class JsonlLocatorFactory
    class ManualPromise
    class LongStandingScope
    class MultiMap
    class Semaphore
    class TimeoutError
    class PlaywrightExtraClass
    class Loader
    class Loader
    class PluginList
    class PlaywrightExtraClass
    class Loader
    class PluginList
    class PlaywrightExtraClass
    class PluginList
    class PluginLifecycleMethods
    class ProxyAgent
    class Browser
    class BrowserContext
    class CDPSession
    class Dialog
    class HTTPRequest
    class HTTPResponse
    class Keyboard
    class Mouse
    class Touchscreen
    class Realm
    class Target
    class WebWorker
    class Locator
    class FunctionLocator
    class DelegatedLocator
    class FilteredLocator
    class MappedLocator
    class NodeLocator
    class RaceLocator
    class CdpConnectionAdapter
    class CDPClientAdapter
    class NoOpTransport
    class BidiBrowser
    class BidiBrowserContext
    class CdpSessionWrapper
    class BrowsingContext
    class BidiConnection
    class BidiDeserializer
    class BidiDialog
    class EmulationManager
    class ExposeableFunction
    class BidiHTTPRequest
    class BidiHTTPResponse
    class BidiKeyboard
    class BidiMouse
    class BidiTouchscreen
    class BidiJSHandle
    class BidiNetworkManager
    class BidiPage
    class BidiRealm
    class Sandbox
    class UnserializableError
    class BidiSerializer
    class BidiTarget
    class BiDiBrowserTarget
    class BiDiBrowsingContextTarget
    class BiDiPageTarget
    class WindowRealm
    class DedicatedWorkerRealm
    class SharedWorkerRealm
    class Accessibility
    class AXNode
    class ARIAQueryHandler
    class Binding
    class CdpBrowser
    class CdpBrowserContext
    class CdpCDPSession
    class ChromeTargetManager
    class Connection
    class Coverage
    class JSCoverage
    class CSSCoverage
    class DeviceRequestPromptDevice
    class DeviceRequestPrompt
    class DeviceRequestPromptManager
    class CdpDialog
    class EmulatedState
    class ExecutionContext
    class FirefoxTargetManager
    class FrameManager
    class FrameTree
    class CdpHTTPRequest
    class CdpHTTPResponse
    class CdpKeyboard
    class CdpMouse
    class CdpTouchscreen
    class IsolatedWorld
    class CdpJSHandle
    class LifecycleWatcher
    class NetworkEventManager
    class NetworkManager
    class CdpPage
    class CdpTarget
    class PageTarget
    class DevToolsTarget
    class WorkerTarget
    class OtherTarget
    class Tracing
    class CdpWebWorker
    class BrowserWebSocketTransport
    class CallbackRegistry
    class Callback
    class ConsoleMessage
    class CustomQueryHandlerRegistry
    class CustomError
    class TimeoutError
    class ProtocolError
    class UnsupportedOperation
    class TargetCloseError
    class EventEmitter
    class EventSubscription
    class FileChooser
    class LazyArg
    class PQueryHandler
    class PierceQueryHandler
    class Puppeteer
    class QueryHandler
    class ScriptInjector
    class SecurityDetails
    class TaskQueue
    class TextQueryHandler
    class TimeoutSettings
    class WaitTask
    class TaskManager
    class XPathQueryHandler
    class PuppeteerURL
    class CustomQuerySelectorRegistry
    class SelectorError
    class PQueryEngine
    class DepthCalculator
    class MutationPoller
    class RAFPoller
    class IntervalPoller
    class ChromeLauncher
    class FirefoxLauncher
    class NodeWebSocketTransport
    class PipeTransport
    class ProductLauncher
    class PuppeteerNode
    class AsyncIterableUtil
    class Deferred
    class Mutex
    class DisposableStack
    class AsyncDisposableStack
    class Browser
    class BrowserContext
    class CDPSession
    class Dialog
    class HTTPRequest
    class HTTPResponse
    class Keyboard
    class Mouse
    class Touchscreen
    class Realm
    class Target
    class WebWorker
    class Locator
    class FunctionLocator
    class DelegatedLocator
    class FilteredLocator
    class MappedLocator
    class NodeLocator
    class RaceLocator
    class CdpConnectionAdapter
    class CDPClientAdapter
    class NoOpTransport
    class BidiBrowser
    class BidiBrowserContext
    class CdpSessionWrapper
    class BrowsingContext
    class BidiConnection
    class BidiDeserializer
    class BidiDialog
    class EmulationManager
    class ExposeableFunction
    class BidiHTTPRequest
    class BidiHTTPResponse
    class BidiKeyboard
    class BidiMouse
    class BidiTouchscreen
    class BidiJSHandle
    class BidiNetworkManager
    class BidiPage
    class BidiRealm
    class Sandbox
    class UnserializableError
    class BidiSerializer
    class BidiTarget
    class BiDiBrowserTarget
    class BiDiBrowsingContextTarget
    class BiDiPageTarget
    class WindowRealm
    class DedicatedWorkerRealm
    class SharedWorkerRealm
    class Accessibility
    class AXNode
    class ARIAQueryHandler
    class Binding
    class CdpBrowser
    class CdpBrowserContext
    class CdpCDPSession
    class ChromeTargetManager
    class Connection
    class Coverage
    class JSCoverage
    class CSSCoverage
    class DeviceRequestPromptDevice
    class DeviceRequestPrompt
    class DeviceRequestPromptManager
    class CdpDialog
    class EmulatedState
    class ExecutionContext
    class FirefoxTargetManager
    class FrameManager
    class FrameTree
    class CdpHTTPRequest
    class CdpHTTPResponse
    class CdpKeyboard
    class CdpMouse
    class CdpTouchscreen
    class IsolatedWorld
    class CdpJSHandle
    class LifecycleWatcher
    class NetworkEventManager
    class NetworkManager
    class CdpPage
    class CdpTarget
    class PageTarget
    class DevToolsTarget
    class WorkerTarget
    class OtherTarget
    class Tracing
    class CdpWebWorker
    class BrowserWebSocketTransport
    class CallbackRegistry
    class Callback
    class ConsoleMessage
    class CustomQueryHandlerRegistry
    class CustomError
    class TimeoutError
    class ProtocolError
    class UnsupportedOperation
    class TargetCloseError
    class EventEmitter
    class EventSubscription
    class FileChooser
    class LazyArg
    class PQueryHandler
    class PierceQueryHandler
    class Puppeteer
    class QueryHandler
    class ScriptInjector
    class SecurityDetails
    class TaskQueue
    class TextQueryHandler
    class TimeoutSettings
    class WaitTask
    class TaskManager
    class XPathQueryHandler
    class PuppeteerURL
    class CustomQuerySelectorRegistry
    class SelectorError
    class PQueryEngine
    class DepthCalculator
    class MutationPoller
    class RAFPoller
    class IntervalPoller
    class ChromeLauncher
    class FirefoxLauncher
    class NodeWebSocketTransport
    class PipeTransport
    class ProductLauncher
    class PuppeteerNode
    class AsyncIterableUtil
    class Deferred
    class Mutex
    class DisposableStack
    class AsyncDisposableStack
    class FunctionLocator
    class FilteredLocator
    class MappedLocator
    class NodeLocator
    class RaceLocator
    class CdpConnectionAdapter
    class CDPClientAdapter
    class NoOpTransport
    class BidiBrowser
    class BidiBrowserContext
    class CdpSessionWrapper
    class BrowsingContext
    class BidiConnection
    class BidiDeserializer
    class BidiDialog
    class BidiElementHandle
    class EmulationManager
    class ExposeableFunction
    class BidiFrame
    class BidiHTTPRequest
    class BidiHTTPResponse
    class BidiKeyboard
    class BidiMouse
    class BidiTouchscreen
    class BidiJSHandle
    class BidiNetworkManager
    class BidiPage
    class BidiRealm
    class Sandbox
    class UnserializableError
    class BidiSerializer
    class BiDiBrowserTarget
    class BiDiBrowsingContextTarget
    class BiDiPageTarget
    class Browser
    class BrowsingContext
    class Navigation
    class WindowRealm
    class DedicatedWorkerRealm
    class SharedWorkerRealm
    class Request
    class Session
    class UserContext
    class UserPrompt
    class Accessibility
    class AXNode
    class ARIAQueryHandler
    class Binding
    class CdpBrowser
    class CdpBrowserContext
    class CdpCDPSession
    class ChromeTargetManager
    class Connection
    class Coverage
    class JSCoverage
    class CSSCoverage
    class DeviceRequestPromptDevice
    class DeviceRequestPrompt
    class DeviceRequestPromptManager
    class CdpDialog
    class CdpElementHandle
    class EmulatedState
    class EmulationManager
    class ExecutionContext
    class FirefoxTargetManager
    class CdpFrame
    class FrameManager
    class FrameTree
    class CdpHTTPRequest
    class CdpHTTPResponse
    class CdpKeyboard
    class CdpMouse
    class CdpTouchscreen
    class IsolatedWorld
    class CdpJSHandle
    class LifecycleWatcher
    class NetworkEventManager
    class NetworkManager
    class CdpPage
    class CdpTarget
    class PageTarget
    class DevToolsTarget
    class WorkerTarget
    class OtherTarget
    class Tracing
    class CdpWebWorker
    class BrowserWebSocketTransport
    class CallbackRegistry
    class Callback
    class ConsoleMessage
    class CustomQueryHandlerRegistry
    class CustomError
    class TimeoutError
    class ProtocolError
    class UnsupportedOperation
    class TargetCloseError
    class EventEmitter
    class EventSubscription
    class FileChooser
    class LazyArg
    class PQueryHandler
    class PierceQueryHandler
    class Puppeteer
    class QueryHandler
    class ScriptInjector
    class SecurityDetails
    class TaskQueue
    class TextQueryHandler
    class TimeoutSettings
    class WaitTask
    class TaskManager
    class XPathQueryHandler
    class PuppeteerURL
    class CustomQuerySelectorRegistry
    class SelectorError
    class PQueryEngine
    class DepthCalculator
    class MutationPoller
    class RAFPoller
    class IntervalPoller
    class ChromeLauncher
    class FirefoxLauncher
    class NodeWebSocketTransport
    class PipeTransport
    class PuppeteerNode
    class ScreenRecorder
    class AsyncIterableUtil
    class Deferred
    class Mutex
    class DisposableStack
    class AsyncDisposableStack
    class PuppeteerExtraPlugin
    class PuppeteerExtraPlugin
    class PuppeteerExtraPlugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class Plugin
    class StealthPlugin
    class Plugin
    class Plugin
    class SmartBuffer
    class SocksClient
    class ReceiveBuffer
    class SocksClientError
    class SocksProxyAgent
    class SourceMapConsumer
    class SourceMapGenerator
    class SourceNode
    class WritableState
    class ReadableState
    class TransformState
    class Pipeline
    class Stream
    class Readable
    class Writable
    class Duplex
    class Transform
    class PassThrough
    class BufferList
    class Source
    class Extract
    class Sink
    class Pack
    class TSError
    class EvalState
    class Client
    class BodyMixin
    class FileSystemBlobStore
    class NativeCompileCache
    class Event
    class CloseEvent
    class ErrorEvent
    class MessageEvent
    class Limiter
    class PerMessageDeflate
    class Receiver
    class Sender
    class WebSocketServer
    class WebSocket
    class Y18N
    class CommandInstance
    class Completion
    class GlobalMiddleware
    class YargsInstance
    class YError
    class YargsParser
    class ArtifactRegistry
    class PerplexityClient
    class GeminiClient
    class GraphStore
    class NotebookLMClient

